name: Deploy
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Summary Header
        run: echo -e '# Build Result\n## Tool Versions' >> $GITHUB_STEP_SUMMARY

      - name: Install mdbook
        run: |
          tag="v0.5.4"
          url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir mdbook
          curl -sSL $url | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH

          latest_tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
          newer_version=""
          if ! [ "${tag}" = "${latest_tag}" ] ; then
            newer_version="\n    - A newer version is available: ${latest_tag}"
          fi
          echo -e "- Installed mdbook ${tag}${newer_version}" >> $GITHUB_STEP_SUMMARY

      - name: Install mdbook-linkcheck2
        run: |
          tag="v0.13.0"
          url="https://github.com/marxin/mdbook-linkcheck2/releases/download/${tag}/mdbook-linkcheck2-x86_64-unknown-linux-gnu.tar.gz"
          curl -sSL $url | tar -xz --directory=./mdbook

          latest_tag=$(curl 'https://api.github.com/repos/marxin/mdbook-linkcheck2/releases/latest' | jq -r '.tag_name')
          newer_version=""
          if ! [ "${tag}" = "${latest_tag}" ] ; then
            newer_version="\n    - A newer version is available: ${latest_tag}"
          fi
          echo -e "- Installed mdbook-linkcheck2 ${tag}${newer_version}" >> $GITHUB_STEP_SUMMARY

      - name: Build Book
        run: mdbook build

      # A pull request builds and link-checks the book but does not deploy it.
      - name: Setup Pages
        if: github.event_name != 'pull_request'
        uses: actions/configure-pages@v4

      - name: Upload artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'book/html'

      - name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request'
        id: deployment
        uses: actions/deploy-pages@v4
